//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRD.Dominio.Modelo.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class CRD_Analistas
    {
        public int IdAnalista { get; set; }
        public int IdEstadoTipoProceso { get; set; }
        public string UsuarioLN { get; set; }
        public string Nombre { get; set; }
        public Nullable<bool> Activo { get; set; }
    
        public virtual CRD_EstadoTipoProcesos CRD_EstadoTipoProcesos { get; set; }
    }
}
